# Introdução ao NumPy
NumPy é uma biblioteca para cálculos numéricos em Python. Ele permite trabalhar com arrays e matrizes de forma rápida e eficiente.

In [ ]:
import numpy as np

## Criando Arrays
Um **array** é semelhante a uma lista, mas otimizado para operações matemáticas.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Tipo dos elementos:", arr.dtype)

Array: [1 2 3 4 5]
Tipo dos elementos: int64


## Comparando com listas
NumPy permite operações matemáticas vetorizadas, sem precisar de loops.

In [ ]:
lista = [1, 2, 3, 4, 5]
print([x*2 for x in lista])  # Usando lista normal
print(arr*2)                 # Usando NumPy (mais simples e rápido)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


## Matrizes
Arrays multidimensionais são usados para representar matrizes.

In [ ]:
matriz = np.array([[1, 2], [3, 4]])
print("Matriz:\n", matriz)
print("Transposta:\n", matriz.T)
print("Produto matricial:\n", np.dot(matriz, matriz))

Matriz:
 [[1 2]
 [3 4]]
Transposta:
 [[1 3]
 [2 4]]
Produto matricial:
 [[ 7 10]
 [15 22]]


## Funções úteis
NumPy possui várias funções prontas para cálculos estatísticos e geração de arrays.

In [ ]:
print("Zeros:\n", np.zeros((2,2)))
print("Ones:\n", np.ones((3,3)))
print("Aleatórios:\n", np.random.randint(0,10,(3,3)))
print("Média do array:", arr.mean())
print("Soma do array:", arr.sum())

Zeros:
 [[0. 0.]
 [0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Aleatórios:
 [[6 0 9]
 [2 4 5]
 [2 8 3]]
Média do array: 3.0
Soma do array: 15
